namespace Codecool.DungeonCrawl
{
    public enum TileType
    {
        Empty,
        Wall,
        Floor,
        Player,
        Skeleton,
        UIborderVerticalLeft,
        UIborderHorizontalTop,
        UIborderVerticalRight,
        UIborderHorizontalBottom,
        UIborderCornerTopLeft,
        UIborderCornerTopRight,
        UIborderCornerBottomLeft,
        UIborderCornerBottomRaight,
        EmptyInventorySlot,
        HealingPotion,
        WoodenShield,
        ManaPotion,
        IronChestplate,
        Sword,
        Key,
        Armor,
        Consumable,
        Hammer,
        Arrows
    }
}
